# These are supported funding model platforms
#
# If you would like to support ShotFlow development, please
# uncomment and fill in your preferred platform(s).

# github: # Replace with up to 4 GitHub Sponsors usernames
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name
# custom: # Replace with a single custom sponsorship URL
