blank_issues_enabled: false
contact_links:
  - name: ShotFlow Discussions
    url: https://github.com/weed33834/ShotFlow/discussions
    about: 请在此提问和讨论（Please ask questions and start discussions here）
