"""add case_studies

Revision ID: acb1c452945a
Revises: 275fdff59f00
Create Date: 2026-07-03 07:33:21.000535
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "acb1c452945a"
down_revision: Union[str, None] = "275fdff59f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_studies",
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.Column("cover_image", sa.String(length=512), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_case_studies_project_id"), "case_studies", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_case_studies_slug"), "case_studies", ["slug"], unique=True)
    op.create_index(op.f("ix_case_studies_status"), "case_studies", ["status"], unique=False)
    op.create_index(op.f("ix_case_studies_title"), "case_studies", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_studies_title"), table_name="case_studies")
    op.drop_index(op.f("ix_case_studies_status"), table_name="case_studies")
    op.drop_index(op.f("ix_case_studies_slug"), table_name="case_studies")
    op.drop_index(op.f("ix_case_studies_project_id"), table_name="case_studies")
    op.drop_table("case_studies")
    # ### end Alembic commands ###
